<?php 
$filter = $this->frm_search;
$dayin_khmer = $this->day_inkhmer;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();	
$db = new Report_Model_DbTable_DbLoan();

$tran = $this->tranarea;
$client = $this->client;											
?>
<?php  $end_dat=$this->date_show; ?>
<?php 
$db_keycode = new Application_Model_DbTable_DbKeycode();
$key_code= $db_keycode->getSystemSetting(9);
$free_day=$key_code['value'];
?>
<style>
.hover:hover{background: #ccc;}
</style>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php  echo $tr->translate("REPORT_LOAN_COLLECT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
 <div style="height: auto; width:29cm; margin: 0 auto;">
 <form method="post">
	<table width="100%">
		<tr>
			<td><?php echo $filter->getElement('adv_search');?></td>
			<td><?php echo $filter->getElement('branch_id');?></td>
			<td><?php echo $filter->getElement('client_name');?></td>
			<td><?php echo $filter->getElement('co_id');?></td>
		</tr>
		<tr>
			
			<td><?php echo $filter->getElement('start_date');?></td>
			<td><?php echo $filter->getElement('end_date');?></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
	</form>
 </div>
<div style=" width:31cm; min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 5px;">
	<div id="divPrint">
	<style>
.style{
	line-height: 20px;font-size: 9px !important;
	font-family: 'Khmer OS Battambang';
}
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
th{padding: 5px;}
</style>
<div id="exportExcel">
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
	                	<td width="60%" valign="top">
	                	<ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("ចំណាត់ថ្នាក់ឥណទានមធ្យម");?></li>
                			<li style="text-align:center; font-size:13px;"><?php echo date("D-d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));?></li>
                		</ul>
                    </td>
	                    <td width="20%"></td>
	                </tr>
	                <?php 
	                ?> 
	                <tr>
	                	<td colspan="3">
	                		<table width="100%">
	                			<tr class='style'>
	                				<td width="40%">
	                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
	                				</td>
	                				<td></td>
	                				
				                </tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td>
	            <table  border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%">
	                 <tr class="style" align="center" bgcolor="#ccc" style="white-space: nowrap;">
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("NUM");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("BRANCH_NAME");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("ឈ្មោះមន្ត្រីឥណទាន");?></td>
	                    <td rowspan="2" style="padding:0px 2px;"><?php echo $tr->translate("BRANCH_NAME");?></td>
	                    <td colspan="4" style="padding:0px 2px;"><?php echo $tr->translate("ឥណទានដែលបានបញ្ចេញក្នុងគ្រា");?></td>
	                    <td colspan="4" style="padding:0px 2px;"><?php echo $tr->translate("សមតុល្យឥណទានគិតដល់ថ្ងៃចុងគ្រា");?></td>
	                    <td colspan="3" ><?php echo $tr->translate("ចំណូលឥណទានក្នុងគ្រា");?></td>
	                    <!--<td rowspan="2" style="padding:0px 2px;"><?php //echo $tr->translate("TIME_COLLECT");?></td>-->
	                    <td colspan="3" style="padding:0px 2px;"><?php echo $tr->translate("ហានិភ័យឥណទានដល់ចុងគ្រា");?></td>
	                </tr>
	                <tr class="style" bgcolor="#ccc" style="white-space: nowrap;">
	                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("ចំនួន");?></td>
	                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("ទំហំឥណទាន");?></td>
	                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("ទំហំឥណទានមធ្យម");?></td>
	                    <td  style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("អាត្រាការប្រាក់មធ្យម");?></td>
	                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("ចំនួន");?></td>
	                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("សមតុល្យ");?></td>
	                    <td  style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("សមតុល្យមធ្យម");?></td>
	                    <td  style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("អាត្រាការប្រាក់មធ្យម");?></td>
	                    <td  style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("ប្រាក់ដើម");?></td>
	                	<td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("ការប្រាក់");?></td>
	                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("ប្រាក់ពិន័យ");?></td>
	                    <td  style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("ចំនួន");?></td>
	                    <td  style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("សមតុល្យ");?></td>
	                    <td style="text-align:center ;padding:0px 2px;"><?php echo $tr->translate("ភាគរយ");?></td>
	                </tr>
	                <?php $amt_r1 = 0;$tir = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$total_r=0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$total_b=0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$total_d=0;$old_curr='';
		             ?>
	               <?php if(!empty($tran))foreach($tran as $key =>$row){
	                if($old_curr!=$row['currency_type']){
	               	?>
	               <tr>
	               	  <td colspan="18" style="background:#ccc;">ប្រភេទប្រាក់ <?php echo $row["curr_type"];?></td>
	               </tr>
	               <?php }?>
	               	<tr align="center" style="font-size:9px; height: 20px; white-space:nowrap;" class="style hover">
	                    <td ><?php echo ($key+1<10)?"0":"";echo $key+1;?></td>
	                    <td align="left">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
	                    <td ><?php echo $row['co_name'];?></td>
	                    <td align="left">&nbsp;<?php //echo $row['branch_kh'];?>&nbsp;</td>
	                    <?php
// 		                   $db = new Report_Model_DbTable_DbloanCollect();
// 		                   $result = $db->getloanAreaByCO($this->search,$row['currency_type']);
	                    ?>
	                    <td align="left">&nbsp;<?php //echo number_format($result['new_loan'],2);?>&nbsp;</td>
	                    <td align="left">&nbsp;<?php //echo number_format(empty($result['total_release'])?0:$result["total_release"],2);?>&nbsp;</td>
	                    <td align="center" style="white-space: nowrap;"><?php //echo number_format(empty($result['total_release'])?0:($result['total_release']/$result['new_loan']),2);?>&nbsp;</td>
	                    <td align="center">&nbsp;<?php ///echo number_format(empty($result['total_interest_rate'])?0:($result['total_interest_rate']/$result['new_loan']),2);?>&nbsp;</td>
	                    
	                    <td align="left">&nbsp;<?php echo $row['new_loan'];?>&nbsp;</td>
	                    <td align="left">&nbsp;<?php echo $row['total_release'].$row["curr_type"];?>&nbsp;</td>
	                    <td align="left" style="min-width:60px;">&nbsp;<?php echo number_format($row['total_release']/$row['new_loan'],2);?>&nbsp;</td>
	                    <td align="left" style="white-space: nowrap;">&nbsp;<?php echo number_format($row['total_interest_rate']/$row['new_loan'],2);?>&nbsp;</td>
	                    
	                    <td align="center">&nbsp;<?php //echo str_replace('.00', '', number_format($row['total_interest_after'],2));?>&nbsp;</td>
	                    <td align="center">&nbsp;</td>
	                   	<td align="center">&nbsp;<?php //echo str_replace('.00', '', number_format($row['service_charge'],2));?>&nbsp;</td>
	                    <td></td>
	                   <td></td>
	                   <td>&nbsp;&nbsp;</td>
	                </tr>
		                <?php 
		                $old_curr = $row['currency_type'];
// 				               if($row['currency_type']==1){
// 				               		$amt_r1 = $amt_r1+$row['principle_after'];
// 				               		$tir = $tir+$row['total_interest_after'];
// 				               		$amt_r3 = $amt_r3+$penelize;
// 				               		$amt_r4 = $amt_r4+$total_payment;
// 				               		$amt_r5 = $amt_r5+$row['service_charge'];
// 				               		$total_r=$amt_r4;
// 				               }elseif($row['currency_type']==2){
// 									$amt_d1 = $amt_d1+$row['principle_after'];
// 									$amt_d2 = $amt_d2+$row['total_interest_after'];
// 									$amt_d3 = $amt_d3+$penelize;
// 									$amt_d4 = $amt_d4+$total_payment;
// 									$amt_d5 = $amt_d5+$row['service_charge'];
// 									$total_d=$amt_d4;
// 				               }else{
// 				               		$amn_b1 = $amn_b1+$row['principle_after'];
// 									$amn_b2 = $amn_b2+$row['total_interest_after'];
// 									$amn_b3 = $amn_b3+$penelize;
// 									$amn_b4 = $amn_b4+$total_payment;
// 									$amn_b5 = $amn_b5+$row['service_charge'];
// 									$total_b=$amn_b4;
// 				               }
		               ?>
	                <?php }?>
	            </table>
	            <div style="height:10px;"></div>
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
                 <tr class="style" bgcolor="#ccc" style="font-weight:bold; line-height: 24px; text-align: center; font-size:12px;font-family: 'Khmer OS Content';">
                    <td style="font-size: 12px;"></td>
                    <th style="font-size: 12px;"><?php echo $tr->translate("OS_AMOUNT");?></th>                    
                    <th style="font-size: 12px;"><?php echo $tr->translate("INTEREST");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("SERVICE_CHARGE");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("TOTAL");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($tir,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_r,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($total_b,2);?>&nbsp;</td>
                </tr>
              </table>
	    	</td>
	    </tr>
	</table>
	<!-- Loan late section -->
</div>